### ISSUE TITLE
How to organize this repo?

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/coding-club#1]
When starting a coding club, we just need to have a single - easy to find - URL where everyone can navigate to and provides the gate to all material needed for that session. This could be the homepage of our coding club website. To do so, I would organize the material as following:

- static website (docs folder): I think both hugo and jekyll framework can be used to generate the website.
    * concept page (manifesto)
    * get started page => can be used by starters each session 
        * folder structure (src/data)
        * rstudio project concept
        * relative path usage
    * session overview page - for each session
        * topic
        * link slideshow
        * link hackmd
        * (I think a page for each session is overkill)

- slideshows: HTML based slideshows. I prefer remark instead of Rmarkdown as this is a single file and no conversion required, hence easier to update:
    * no 'what have I done' section anymore
    * no more setup slides => move to general info/get started page
    * focus on 3 challenges
    * all links to data need to initiate download
    * all links to scripts need to either download or link to raw version

- structure repo needs to be useful for management AND as cloned version to work in

```
    |_ data
        |_ YYYYMMDD_filename.csv
        |_ ...
    |_ src
        |_ YYYYMMDD_filename.R
        |_ ...
    |_ docs (coding club website)
        |_ manifesto.md
        |_ getting_started.md
        |_ worklfow  <- organization workflow 
        |_ sessions
            |_sessions.md
            |_ YYYYMMDD_topicname.html (slides)
            |_ YYYYMMDD_topicname.html (slides)
            |_ ...
        |_ images
    |_ cheatsheet <- required?
    |_ .Rproj  <- ignored or not? I would say ignore in this case
    |_ .gitignore
    |_ .github
        |_ CODE_OF_CONDUCT.md
        |_ CONTRIBUTING.md
```

@damianooldoni, what do you think?

**Comment by peterdesmet** [comment]
Would it make sense - cf. tutorials - to combine all files for a session in a yyyymmdd directory, rather than spreading it over docs, src and data?

**Comment by stijnvanhoey** [comment]
@peterdesmet as we are recycling a lot the data sets for multiple coding clubs, a _directory per session_ is not working out that well. Moreover, we opt to have a single `coding club`  Rstudio project for all sessions and hence provide the typical `src` and `data` structure for that project.

**Comment by peterdesmet** [comment]
Ok, makes sense. In that case, some stray observations:

- `sessions/sessions.md` -> rename to `sessions/index.md`
- `manifesto.md`: if this is homepage, rename to `index.md`. If this is not homepage, add new `index.md`
- Advise to use short, lowercase, underscored `TOPICNAME` or drop it altogether from `YYYYMMDD_TOPICNAME.html` (and just use dates)
- `src/YYYYMMDD_NAME.R`: is `NAME` = `TOPICNAME`?
- `data/YYYYMMDD_NAME.csv`: if data are going to be reused, I would not add date in name.
- Directly starting download for data + scripts: not sure a forced download is actually possible, as GitHub displays raw data in browser: https://raw.githubusercontent.com/inbo/coding-club/master/README.md
- I would bundle @damianooldoni suggestion for `agenda.md` with `sessions/index.md`, adding the location as a column.

**Comment by stijnvanhoey** [comment]
- `index.md` files instead of manifesto/sessions -> check
- lowercase names is indeed preferred, I'll keep the topicname in the slide name as this was explicitly asked by participants
- `* src/YYYYMMDD_filename.R` let's keep some flexibility in the file naming here as we will changing number of files for each session. Refer to challenge number if relevant is probably good option e.g. `20180124_challenge_1.R`
- `* data/YYYYMMDD_NAME.csv` I'd like to have a clue on first-time used in coding club when preparing new coding clubs, so keep dates used
-

**Comment by stijnvanhoey** [comment]
some website/slideqhow tryouts
https://inbo.github.io/coding-club
https://inbo.github.io/coding-club/sessions/ with links to slideshows, a slideshow example is available https://github.com/inbo/coding-club/blob/master/docs/sessions/20190226_gis_vector.html

**Comment by stijnvanhoey** [comment]
closing here, as we have our structure!
