### ISSUE TITLE
Add coding-club.Rproj to repo

### ISSUE THREAD

**Issue by peterdesmet** [inbo/coding-club#11]
Useful for git users who clone this repo https://inbo.github.io/coding-club/gettingstarted.html

**Comment by damianooldoni** [comment]
In the note for git-users in section _First time setup_ it's written the following:

> When familiar with Git, you can setup a coding club using the git-integration of Rstudio. Go to File and choose New Project.... Pick Version control, next Git and fill in the URL of the coding club in the Repository URL: https://github.com/inbo/coding-club

So, not needed, I think.

**Comment by damianooldoni** [comment]
Still, the .Rproj file has been added 5 years ago as asked by @peterdesmet. So, issue can be closed as completed.
