### ISSUE TITLE
don't use setwd() to an absolute path

### ISSUE THREAD

**Issue by ThierryO** [inbo/coding-club#13]
https://github.com/inbo/coding-club/blob/2aedef27a12d5677dd7602c431f6ac466b91a9bc/src/20200225_create_messy_project.R#L37

This will only work when the path is available and on Windows.

**Comment by SanderDevisscher** [comment]
@hansvancalster intentional ?

**Comment by hansvancalster** [comment]
@SanderDevisscher @ThierryO yes this is intentional and part of the exercise
