### ISSUE TITLE
Remarks on slides and excercises 2022-08-30

### ISSUE THREAD

**Issue by EmmaCartuyvels1** [inbo/coding-club#32]
@damianooldoni good job on the slides and challenges!

A few small remarks on the coding club of tomorrow:
- [x] the date is wrong on the sessions page
- [x] the intermezzo plots two different graphs in the code, in the slides you seem to have simplified them
- [x] missing a `+ geom_point` in the code (challenge 2.2)?

**Comment by damianooldoni** [comment]
Thanks @EmmaCartuyvels1!

1. Date on sessions page is corrected now.
2. Yes, in the slides I show one plot. No space for two plots. In R code, I replace the comment `# First plot` with `# First plot (shown in slides)`. It should be enough. This part is also given live so it should be easy to follow.
3.  Indeed! I added it to the code

Thanks to check code and slides! We are ready for a new coding club session 🥳
